definitions:
  caches:
      yarncustom: /root/.yarn-cache
  steps:

    - step: &build-test
        name: Build and Test
        image: python:3.7.3
        caches:
          - pip
        script:
          - pip install virtualenv

          - virtualenv venv
          - source venv/bin/activate
          - pip install -r requirements.txt

          - nosetests -sv --with-xunit --xunit-file=nosetests.xml --with-xcoverage --xcoverage-file=coverage.xml --cover-package=src --cover-branches
        artifacts:
          - coverage.xml
          - nosetests.xml

    - step: &sonar-scan
        image: naeemark/sonar-scanner:latest
        name: Sonar -> Analyse, Push 
        script:
          - export SONAR_URL=$SONAR_URL
          - export SONAR_TOKEN=$SONAR_TOKEN
          - export SONAR_ANALYSIS_MODE=publish
          - bitbucket-sonar-scanner

    - step: &deploy-dev
        caches:
          - node
          - yarncustom
        image: naeemark/node-awscli:latest
        name: Deploy -> Dev
        script:
          - apk add python3
          - yarn add serverless --dev
          - node_modules/.bin/sls deploy --stage dev

    - step: &deploy-prod
        caches:
          - node
          - yarncustom
        image: naeemark/node-awscli:latest
        name: Deploy -> Prod
        trigger: manual
        script:
          - apk add python3
          - yarn add serverless --dev
          - node_modules/.bin/sls deploy --stage prod

pipelines:
  branches:
    develop:
      - step: *build-test
      - step: *deploy-dev
    master:
      - step: *build-test
      - step: *sonar-scan
      - step: *deploy-prod

  tags:
    v*:
      - step: *build-test
      - step: *sonar-scan
      - step: *deploy-prod
