# Welcome to Serverless!

service: klarna-serverless
app: klarna-serverless-app
org: naeemfrt

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: src/handler.hello
    tracing: true
    events:
      - http:
          method: get
          path: api/v1/hello
          cors: true
